### PR TITLE
nvme: copy chunk info to mptr of vector reset

### PR DESCRIPTION
**Pull request by youngtack**
to recover the mistake done through github web gui

### CODE REVIEW

**Comment by MatiasBjorling** [comment]
Uh, what was the mistake? I've pulled in the previous PR?

**Comment by youngtack** [comment]
Yes, the prevous patch is missing a closing parentheses. Sorry to find it lately.

**Comment by MatiasBjorling** [comment]
Good point. I've fixed it up.

**Comment by youngtack** [comment]
Thanks a lot. Now I'm more familiar with the interaction between git cli and github web ui.
I will be more careful for any upcoming pull request.

**Pull request closed without merging**
