### PR TITLE
nvme: fix slba in chunk_meta table

### PR DESCRIPTION
**Pull request by birkelund**

### CODE REVIEW

**Comment by birkelund** [comment]
I wanted to keep the convention of calling it `ppa` and `pos` because this is the reverse of the function `int64_t lnvm_chunk_pos_from_ppa(LnvmCtrl *ln, uint64_t ppa)`. And yes, `pos` is the position in the `chunk_meta` array that is initialized in the `void lnvm_chunk_meta_init(...)` function.

**Comment by MatiasBjorling** [comment]
Heh, I meant, that it properly should be called cno or similar.

I've pushed another pull req that cleans up the PPA and renames it to LBA, and also fixes up the existing function. Can you rebase your function on top of that after you've taken a look at it?

**Comment by birkelund** [comment]
@MatiasBjorling done, rebased.

**Comment by MatiasBjorling** [comment]
Thanks

**Pull request merged**
